# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  Build_and_Deploy:
    name: set up environment
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      
      - name : update npm
        run: |
          npm update --location=global npm
          npm update --location=global

      - name: install hexo
        run: |
          npm install --location=global hexo
          git clone https://github.com/liuyib/hexo-theme-stun.git themes/stun
          npm install --save hexo-renderer-pug
          npm un hexo-renderer-marked --save
          npm i hexo-renderer-markdown-it-plus --save
          npm install hexo-generator-sitemap --save
          npm install hexo-generator-search --save
          npm install hexo-deployer-git --save
          npm install
          mv -f ./localsearch.pug ./themes/stun/layout/_third-party/search/localsearch.pug
          hexo clean
          hexo g
          cd public
          rm -f README.html
          cd ..

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public